# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fargo < Formula
  desc "FargoRate billiards rating CLI"
  homepage "https://github.com/rgstephens/fargo-skill"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.3.5/fargo_darwin_amd64.tar.gz"
      sha256 "02a98abde633620404aeeafdf459f026a45e9de4abf66b3ace6a91e88784b6e3"

      define_method(:install) do
        bin.install "fargo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.3.5/fargo_darwin_arm64.tar.gz"
      sha256 "9fbf430a1961c74148b14edc860648885c5c0c952255c8f3e4136345ece7d18a"

      define_method(:install) do
        bin.install "fargo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.3.5/fargo_linux_amd64.tar.gz"
      sha256 "b05ce5f7941fc64930a3c3920d4dffffdd4ba8a71184401c5be1eeff2521ce7d"
      define_method(:install) do
        bin.install "fargo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.3.5/fargo_linux_arm64.tar.gz"
      sha256 "33cd4dfa2bd984e7189416259df69e1ab6b3c60a5a63336cb029301a03b17e80"
      define_method(:install) do
        bin.install "fargo"
      end
    end
  end

  test do
    system "#{bin}/fargo", "--version"
  end
end
