# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fargo < Formula
  desc "FargoRate billiards rating CLI"
  homepage "https://github.com/rgstephens/fargo-skill"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.4.0/fargo_darwin_amd64.tar.gz"
      sha256 "53cec9b7d190d5ab90e3447909c6846d29cc42979fb11da6c25a2e5393ddf72e"

      define_method(:install) do
        bin.install "fargo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.4.0/fargo_darwin_arm64.tar.gz"
      sha256 "1de2cab48760e92f4286ba738f963248cea211986704b5a0cb8d5f6e27e93177"

      define_method(:install) do
        bin.install "fargo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.4.0/fargo_linux_amd64.tar.gz"
      sha256 "62ab5336c09722dde5a3c936dbfb99c9e635b3f87e87f77f2fee82ee7034df08"
      define_method(:install) do
        bin.install "fargo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/fargo-skill/releases/download/v0.4.0/fargo_linux_arm64.tar.gz"
      sha256 "0fbe6a4daea29b2f872d69df7bbf11c2c0b307f9320c331ea8d2afd80c215a3d"
      define_method(:install) do
        bin.install "fargo"
      end
    end
  end

  test do
    system "#{bin}/fargo", "--version"
  end
end
