# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghin < Formula
  desc "CLI for the GHIN golf handicap API"
  homepage "https://github.com/rgstephens/ghin"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgstephens/ghin/releases/download/v0.2.0/ghin_0.2.0_darwin_amd64.tar.gz"
      sha256 "e3dfe50f056f1c3c8e4a40f0226db9f6e12e834e6b5cbbd117682757f0e10ff8"

      define_method(:install) do
        bin.install "ghin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgstephens/ghin/releases/download/v0.2.0/ghin_0.2.0_darwin_arm64.tar.gz"
      sha256 "42b0f94a9f291671d24e8567e8c6dde78a9d4b026c936f63f60c6df87acaea3a"

      define_method(:install) do
        bin.install "ghin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/ghin/releases/download/v0.2.0/ghin_0.2.0_linux_amd64.tar.gz"
      sha256 "bd5f9ee021cd8ada89fd02dfbf586d465cc845aa15f4f6e21aa952aa82cf7316"
      define_method(:install) do
        bin.install "ghin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/ghin/releases/download/v0.2.0/ghin_0.2.0_linux_arm64.tar.gz"
      sha256 "dd1a671c4646ec99840140cdd8458f32ba4597955f0103ad0fb53f158c5f4b73"
      define_method(:install) do
        bin.install "ghin"
      end
    end
  end

  test do
    system "#{bin}/ghin", "--version"
  end
end
