# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poeusage < Formula
  desc "Monitor your Poe API point balance and usage history"
  homepage "https://github.com/rgstephens/poeusage"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgstephens/poeusage/releases/download/v1.0.3/poeusage_1.0.3_darwin_amd64.tar.gz"
      sha256 "cb270d6a797777f5525e06b89938e63246184fe34a8e99aeefd5ec2c37cb7648"

      define_method(:install) do
        bin.install "poeusage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgstephens/poeusage/releases/download/v1.0.3/poeusage_1.0.3_darwin_arm64.tar.gz"
      sha256 "fdf0a59f185d3e1b06b477d54cd39373746e485791872aa0876eb2da705884be"

      define_method(:install) do
        bin.install "poeusage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/poeusage/releases/download/v1.0.3/poeusage_1.0.3_linux_amd64.tar.gz"
      sha256 "eac5317a30e2de4e0395c4ff017a3277e7fe3eb68def5bb4bd3bd6c24fb1e3f3"
      define_method(:install) do
        bin.install "poeusage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgstephens/poeusage/releases/download/v1.0.3/poeusage_1.0.3_linux_arm64.tar.gz"
      sha256 "e4526e4f41e3703b332558f1814aac96e5f9f30cdfd4c7f651830c18ad18ef94"
      define_method(:install) do
        bin.install "poeusage"
      end
    end
  end

  test do
    system "#{bin}/poeusage", "--version"
  end
end
